FEATURES = [
    'NODE_TYPE',
    'CMD_LINE_TYPE',
    'LOGIN_NAME_VERSION',
    'EUID_VALUE',
    'BINARY_FILE_PATH'
]

FEATURES_ONE_HOT = [
    'NODE_FILE',
    'NODE_PROCESS',
    'NODE_SOCKET',
    'CMD_LINE_SLEEP',
    'CMD_LINE_CRON',
    'CMD_LINE_POSTGRES',
    'CMD_LINE_SSH',
    'CMD_LINE_RM',
    'CMD_LINE_DD',
    'CMD_LINE_CP',
    'CMD_LINE_CAT',
    'CMD_LINE_MV',
    'CMD_LINE_GZIP',
    'CMD_LINE_GUNZIP',
    'CMD_LINE_FIND',
    'LOGIN_NAME_STEVE',
    'LOGIN_NAME_OPERATOR',
    'LOGIN_NAME_ROOT',
    'LOGIN_NAME_LARIAT',
    'LOGIN_NAME_DARPA',
    'LOGIN_NAME_NONE',
    'EUID_0',
    'EUID_1',
    'EUID_2',
    'EUID_1004',
    'EUID_NONE'
    'BINARY_FILE_USR',
    'BINARY_FILE_OPT',
    'BINARY_FILE_TMP',
    'BINARY_FILE_VAR'
]

LABELS = [
    'SSH',
    'APACHE'
]
